# Generated by Django 5.1.3 on 2026-08-12 03:27

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaEncuesta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('NPS', 'NPS'), ('CSAT', 'CSAT'), ('MIXTO', 'Mixto')], max_length=10)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('preguntas', models.JSONField(default=dict)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plantilla de encuesta',
                'verbose_name_plural': 'Plantillas de encuesta',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('url_qr', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_respuesta', models.DateTimeField(blank=True, null=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuestas', to='businesses.local')),
                ('plantilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveys.plantillaencuesta')),
            ],
            options={
                'verbose_name': 'Encuesta',
                'verbose_name_plural': 'Encuestas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaEncuesta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('csat_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('nps_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('enviado_google', models.BooleanField(default=False)),
                ('datos', models.JSONField(blank=True, null=True)),
                ('sentimiento', models.CharField(blank=True, choices=[('POSITIVO', 'Positivo'), ('NEUTRO', 'Neutro'), ('NEGATIVO', 'Negativo')], max_length=10, null=True)),
                ('score_sentimiento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dispositivo', models.CharField(blank=True, max_length=100, null=True)),
                ('navegador', models.CharField(blank=True, max_length=100, null=True)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='surveys.encuesta')),
            ],
            options={
                'verbose_name': 'Respuesta de encuesta',
                'verbose_name_plural': 'Respuestas de encuesta',
                'ordering': ['-fecha_respuesta'],
            },
        ),
        migrations.CreateModel(
            name='PreguntaRespuesta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pregunta_texto', models.CharField(max_length=500)),
                ('respuesta_texto', models.TextField(blank=True, null=True)),
                ('respuesta_valor', models.IntegerField(blank=True, null=True)),
                ('respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_respuestas', to='surveys.respuestaencuesta')),
            ],
            options={
                'verbose_name': 'Pregunta y respuesta',
                'verbose_name_plural': 'Preguntas y respuestas',
            },
        ),
    ]
