# Generated by Django 5.1.3 on 2026-08-25 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_unico', models.SlugField(help_text='Identificador único para uso interno en templates y código.', max_length=80, unique=True, verbose_name='Código Único')),
                ('categoria', models.CharField(choices=[('PLANES', 'Planes y Suscripciones'), ('PAGOS', 'Pagos y Facturación'), ('BENCHMARK', 'Benchmark y Competencia'), ('CSAT_NPS', 'CSAT / NPS y Encuestas'), ('RESEÑAS_GOOGLE', 'Reseñas Google'), ('ONBOARDING', 'Onboarding y Bienvenida')], db_index=True, default='ONBOARDING', max_length=20, verbose_name='Categoría')),
                ('nombre', models.CharField(max_length=180, verbose_name='Nombre Plantilla')),
                ('asunto_email', models.CharField(help_text='Variable placeholders: {{negocio}}, {{usuario}}, {{local}}, {{kpi}}, etc.', max_length=180, verbose_name='Asunto Email')),
                ('cuerpo_texto_plano', models.TextField(blank=True, default='', help_text='Versión texto plano sin HTML para clientes de correo antiguos.', verbose_name='Cuerpo Texto Plano')),
                ('cuerpo_html', models.TextField(help_text='Puedes usar sintaxis Django Template: {{variable}}, {% for %}, {{nombre|upper}}.', verbose_name='Cuerpo HTML (Django Template)')),
                ('variables_esperadas', models.JSONField(blank=True, default=list, help_text="Array JSON con nombres de variables a documentar, ej: ['negocio','local','nps_score'].", verbose_name='Variables Esperadas')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activa')),
                ('orden', models.PositiveSmallIntegerField(db_index=True, default=1, verbose_name='Orden')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Plantilla Notificación',
                'verbose_name_plural': 'Plantillas Notificaciones',
                'ordering': ['categoria', 'orden', 'nombre'],
                'indexes': [models.Index(fields=['categoria', 'activo'], name='notificatio_categor_ad0ac2_idx')],
            },
        ),
    ]
