# Generated by Django 5.1.3 on 2026-08-12 03:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaEstatica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('publicado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Página estática',
                'verbose_name_plural': 'Páginas estáticas',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='PoliticaLegal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('TERMINOS_CONDICIONES', 'Términos y condiciones'), ('POLITICA_PRIVACIDAD', 'Política de privacidad'), ('POLITICA_COOKIES', 'Política de cookies')], max_length=30)),
                ('version', models.CharField(max_length=50)),
                ('fecha_vigencia', models.DateField()),
                ('contenido', models.TextField()),
                ('publicado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Política legal',
                'verbose_name_plural': 'Políticas legales',
                'ordering': ['tipo', '-fecha_vigencia'],
                'unique_together': {('tipo', 'version')},
            },
        ),
    ]
