# Generated by Django 5.1.3 on 2026-08-12 03:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiccionarioSentimiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('palabra', models.CharField(max_length=100, unique=True)),
                ('polaridad', models.CharField(choices=[('POSITIVO', 'Positivo'), ('NEUTRO', 'Neutro'), ('NEGATIVO', 'Negativo')], max_length=10)),
                ('peso', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('categoria', models.CharField(blank=True, choices=[('MODISMO_CHILENO', 'Modismo chileno'), ('NEGACION', 'Negación'), ('INTENSIFICADOR', 'Intensificador'), ('GENERAL', 'General')], max_length=20, null=True)),
                ('ejemplo_uso', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Diccionario de sentimiento',
                'verbose_name_plural': 'Diccionario de sentimientos',
                'ordering': ['palabra'],
            },
        ),
        migrations.CreateModel(
            name='HistorialCorreccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texto_original', models.TextField()),
                ('clasificacion_anterior', models.CharField(choices=[('POSITIVO', 'Positivo'), ('NEUTRO', 'Neutro'), ('NEGATIVO', 'Negativo')], max_length=10)),
                ('clasificacion_nueva', models.CharField(choices=[('POSITIVO', 'Positivo'), ('NEUTRO', 'Neutro'), ('NEGATIVO', 'Negativo')], max_length=10)),
                ('modelo_origen', models.CharField(max_length=100)),
                ('fecha_correccion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de corrección',
                'verbose_name_plural': 'Historiales de corrección',
                'ordering': ['-fecha_correccion'],
            },
        ),
    ]
