# Generated by Django 5.1.3 on 2026-08-12 03:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='MVP_BASICO', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_uf', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_clp', models.IntegerField(blank=True, null=True)),
                ('moneda', models.CharField(choices=[('CLP', 'Pesos Chilenos'), ('UF', 'Unidad de Fomento')], default='CLP', max_length=10)),
                ('locales_permitidos', models.IntegerField(default=1)),
                ('usuarios_permitidos', models.IntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACTIVA', 'Activa'), ('VENCIDA', 'Vencida'), ('SUSPENDIDA', 'Suspendida'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_vencimiento', models.DateTimeField()),
                ('proximo_ciclo', models.DateTimeField(blank=True, null=True)),
                ('renovacion_automatica', models.BooleanField(default=True)),
                ('cancelada_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelacion', models.CharField(blank=True, max_length=255, null=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to='businesses.negocio')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suscripciones', to='billing.plan')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='RegistroCobranza',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('RECORDATORIO_VENCIMIENTO', 'Recordatorio de Vencimiento'), ('SUSPENSION', 'Suspensión'), ('AVISO_VENCIMIENTO', 'Aviso de Próximo Vencimiento'), ('RECUPERACION', 'Recuperación de Cobro'), ('CONFIRMACION_PAGO', 'Confirmación de Pago')], max_length=50)),
                ('enviado', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('destinatario', models.CharField(max_length=255)),
                ('asunto', models.CharField(max_length=255)),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_cobranza', to='billing.suscripcion')),
            ],
            options={
                'verbose_name': 'Registro de Cobranza',
                'verbose_name_plural': 'Registros de Cobranza',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flow_order_id', models.CharField(max_length=100, unique=True)),
                ('monto', models.IntegerField()),
                ('moneda', models.CharField(default='CLP', max_length=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('REEMBOLSADO', 'Reembolsado')], default='PENDIENTE', max_length=20)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('comprobante_url', models.CharField(blank=True, max_length=500, null=True)),
                ('datos_webhook', models.JSONField(blank=True, default=dict)),
                ('firma_validada', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='billing.suscripcion')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
