# Generated by Django 5.1.3 on 2026-08-13 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['orden', '-fecha_creacion'], 'verbose_name': 'Plan', 'verbose_name_plural': 'Planes'},
        ),
        migrations.AddField(
            model_name='plan',
            name='caracteristicas',
            field=models.JSONField(blank=True, default=list, help_text='Lista de características del plan en formato JSON: ["📊 Panel de métricas", "📝 Encuestas NPS", ...]'),
        ),
        migrations.AddField(
            model_name='plan',
            name='dias_prueba_gratis',
            field=models.IntegerField(default=365, help_text='Cantidad de días gratuitos al contratar el plan por primera vez.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='es_plan_default',
            field=models.BooleanField(default=False, help_text='Plan que se asigna automáticamente durante el onboarding inicial. Solo puede haber uno activo.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='nombre_mostrar',
            field=models.CharField(blank=True, help_text='Nombre amigable para mostrar en UI (ej: MVP Básico). Si queda vacío usa "nombre".', max_length=100),
        ),
        migrations.AddField(
            model_name='plan',
            name='orden',
            field=models.IntegerField(default=0, help_text='Orden en que aparecen los planes en la UI (menor = primero).'),
        ),
    ]
