# Generated by Django 5.1.3 on 2026-08-17 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_plan_options_plan_caracteristicas_and_more'),
        ('geo', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='costo_local_adicional_clp',
            field=models.IntegerField(default=0, help_text='Costo extra CLP por cada local adicional por sobre locales_gratis_incluidos. (Doc: Basico $30k, Empresarial $25k, Profesional $20k)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='costo_rubro_adicional_clp',
            field=models.IntegerField(default=0, help_text='Costo extra CLP por cada rubro online adicional por sobre rubros_gratis_incluidos. (Doc: Basico $30k, Empresarial $25k, Profesional $20k)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='es_lanzamiento_gratis',
            field=models.BooleanField(default=False, help_text='Marcar para planes de lanzamiento 365 días gratis (MVP demo). NO aparece en listado de precios normales.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='locales_gratis_incluidos',
            field=models.IntegerField(default=3, help_text='Primeros N locales incluidos en el precio base. A partir de N+1 cobra costo_local_adicional_clp por cada uno. Doc: desde 4° local cobra extra (= 3 gratis).'),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_preguntas_encuesta_custom',
            field=models.IntegerField(default=0, help_text='Si tiene_encuestas_custom=True: cantidad máxima de preguntas permitidas por encuesta custom. Doc Profesional = 5.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='rubros',
            field=models.ManyToManyField(blank=True, help_text='Rubros online asociados a este plan (para cross-selling / multi-rubro digital).', related_name='planes', to='geo.rubro'),
        ),
        migrations.AddField(
            model_name='plan',
            name='rubros_gratis_incluidos',
            field=models.IntegerField(default=3, help_text='Primeros N rubros online incluidos en el precio base. A partir de N+1 cobra costo_rubro_adicional_clp por cada uno. (Doc: desde 4° rubro online cobra extra)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='rubros_permitidos',
            field=models.IntegerField(default=3, help_text='Cantidad TOTAL de rubros online permitidos (benchmarking cross-sector / e-commerce).'),
        ),
        migrations.AddField(
            model_name='plan',
            name='tiene_benchmarking_rubro',
            field=models.BooleanField(default=False, help_text='Plan Básico = NO. Empresarial y Profesional = SÍ. Doc: "plan 2 = benchmarking empresas mismo rubro".'),
        ),
        migrations.AddField(
            model_name='plan',
            name='tiene_encuestas_custom',
            field=models.BooleanField(default=False, help_text='Básico / Empresarial = NO. Profesional = SÍ. Doc: "plan 3 = encuestas custom máximo 5 preguntas".'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='locales_permitidos',
            field=models.IntegerField(default=3, help_text='Cantidad TOTAL de locales físicos permitidos (incluye locales gratis antes del cobro extra).'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='usuarios_permitidos',
            field=models.IntegerField(default=2),
        ),
    ]
