# Generated by Django 5.1.3 on 2026-08-25 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_plan_costo_local_adicional_clp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='max_preguntas_adicionales',
            field=models.IntegerField(default=0, help_text='Preguntas adicionales permitidas (fuera del set por rubro). Plan1 = 0, Plan2 = 0, Plan3 = 3.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='tiene_analisis_google',
            field=models.BooleanField(default=True, help_text='Análisis rating Google + reseñas Google + evolución histórica Google. Plan1 = True.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='tiene_benchmark_clientbeat',
            field=models.BooleanField(default=False, help_text='BENCHMARK CLIENTBEAT por rubro (comparativa NPS/CSAT/dimensiones con otros CB de misma comuna/región). Plan3 = True.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='tiene_benchmark_google',
            field=models.BooleanField(default=True, help_text='Benchmark Google contra competencia (rating, nº opiniones, desempate 3 reglas). Plan1 = True.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='tiene_encuestas_custom_rubro',
            field=models.BooleanField(default=False, help_text='Encuestas personalizadas según dimensiones/atributos del rubro (28 rubros Metodología). Plan2 y Plan3 = True.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='tiene_export_excel',
            field=models.BooleanField(default=True, help_text='Exportar métricas a Excel/CSV. Todos los planes = True.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='tiene_notificaciones',
            field=models.BooleanField(default=True, help_text='Notificaciones eventos planes/pagos/benchmark/reseñas/CSAT-NPS. Todos los planes = True.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='tiene_qr_clientbeat',
            field=models.BooleanField(default=False, help_text='QR encuestas NPS y CSAT por local. Plan1 = False. Plan2 y Plan3 = True.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='tiene_segmentacion_demografica',
            field=models.BooleanField(default=False, help_text='Segmentación demográfica clientes (edad, género, etc.) desde QR. Plan2 y Plan3 = True.'),
        ),
    ]
