# Generated by Django 5.1.3 on 2026-08-29 17:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_plan_max_preguntas_adicionales_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CambioPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('motivo', models.CharField(choices=[('UPGRADE_ADMIN', 'Upgrade manual por Admin Soporte'), ('DOWNGRADE_ADMIN', 'Downgrade manual por Admin Soporte'), ('CAMBIO_LOC_AUTO', 'Cambio automático por ajuste de locales'), ('SOLICITUD_DUENO', 'Solicitud del dueño del negocio'), ('BONIFICACION', 'Bonificación / regalo ClientBeat'), ('CORRECION_ADMIN', 'Corrección administrativa'), ('OTRO', 'Otro (especificar en notas)')], default='CORRECION_ADMIN', max_length=30)),
                ('notas', models.TextField(blank=True, help_text='Notas internas Admin Soporte. No visible al cliente.', null=True)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('precio_antes_clp', models.IntegerField(blank=True, help_text='Monto que pagaba antes del cambio', null=True)),
                ('precio_despues_clp', models.IntegerField(blank=True, help_text='Monto que pasa a pagar', null=True)),
                ('dias_prorrateo', models.IntegerField(default=0, help_text='Días de prorrata aplicados en este cambio')),
                ('plan_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cambios_desde', to='billing.plan')),
                ('plan_nuevo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_hacia', to='billing.plan')),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_plan_realizados', to=settings.AUTH_USER_MODEL)),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_plan', to='billing.suscripcion')),
            ],
            options={
                'verbose_name': 'Cambio de Plan',
                'verbose_name_plural': 'Cambios de Plan',
                'ordering': ['-fecha_cambio'],
                'indexes': [models.Index(fields=['suscripcion', 'fecha_cambio'], name='billing_cam_suscrip_fabb0d_idx'), models.Index(fields=['motivo', 'fecha_cambio'], name='billing_cam_motivo_c6812d_idx')],
            },
        ),
    ]
