# Generated by Django 5.1.3 on 2026-09-30 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_cambioplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='disponible_para_venta',
            field=models.BooleanField(default=True, help_text='Si es False, deshabilita la contratación directa y muestra el CTA "Aún no disponible para la venta - Próximamente".'),
        ),
    ]
