# Generated by Django 5.1.3 on 2026-08-13 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('ADMIN_SOPORTE', 'Admin Soporte ClienBeat'), ('DUENO', 'Dueño de Negocio'), ('USUARIO_EQUIPO', 'Usuario de Equipo')], default='USUARIO_EQUIPO', max_length=20, verbose_name='Rol global'),
        ),
    ]
