# Generated by Django 5.1.3 on 2026-08-17 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ejemplo: Metropolitana de Santiago, Valparaíso, Biobío, etc.', max_length=120, unique=True, verbose_name='Nombre de Región')),
                ('codigo_romano', models.CharField(help_text='Ej: RM, I, II, XV, etc.', max_length=8, unique=True, verbose_name='Código Romano / Oficial')),
                ('orden', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Orden de despliegue (1..16)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activa en Onboarding')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Región',
                'verbose_name_plural': 'Regiones',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre del Rubro')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción breve (aparece en onboarding como ayuda al dueño).')),
                ('icono', models.CharField(blank=True, help_text='Clase FontAwesome o emoji para mostrar en UI (ej: fa-mug-hot, 🍕).', max_length=60)),
                ('tipo', models.CharField(choices=[('LOCAL_FISICO', 'Local físico (restaurante, local, comercio)'), ('RUBRO_ONLINE', 'Rubro online / e-commerce / digital'), ('AMBOS', 'Mixto (físico + online)')], db_index=True, default='LOCAL_FISICO', max_length=30, verbose_name='Tipo de Rubro')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo en onboarding (lista desplegable)')),
                ('es_otro', models.BooleanField(default=False, verbose_name='Opción "Otro / No está en la lista"')),
                ('orden', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rubro',
                'verbose_name_plural': 'Rubros',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de Provincia')),
                ('orden', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provincias', to='geo.region', verbose_name='Región')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'ordering': ['region__orden', 'orden', 'nombre'],
                'unique_together': {('region', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de Comuna')),
                ('orden', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunas', to='geo.provincia', verbose_name='Provincia')),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
                'ordering': ['provincia__region__orden', 'provincia__orden', 'orden', 'nombre'],
                'unique_together': {('provincia', 'nombre')},
            },
        ),
    ]
