# Generated by Django 5.1.3 on 2026-08-25 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_en', models.CharField(help_text='Identificador Google Places API: bakery, restaurant, hair_care, etc.', max_length=255, unique=True, verbose_name='Google category (EN)')),
                ('google_es', models.CharField(blank=True, max_length=255, verbose_name='Nombre amigable (ES)')),
                ('has_visible_subratings', models.BooleanField(default=False, help_text='bakery/bar/cafe/restaurant/hair_care/beauty_salon = True (33 principales lo tienen).', verbose_name='Tiene subratings visibles en Google (Food/Service/Atmosphere/...)')),
                ('subratings_examples', models.JSONField(blank=True, default=list, help_text='Ej: ["Food & Drink quality", "Service", "Atmosphere & Ambience"]')),
                ('additional_fields', models.JSONField(blank=True, default=list, help_text='Otros campos Google medibles: ["spend_per_person", "popular_times", ...]')),
                ('documentation_note', models.TextField(blank=True)),
                ('orden', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Google Category',
                'verbose_name_plural': 'Google Categories',
                'ordering': ['orden', 'google_es', 'google_en'],
            },
        ),
        migrations.AddField(
            model_name='rubro',
            name='rubro_principal_1',
            field=models.CharField(choices=[('PRODUCTO', 'Producto'), ('SERVICIO', 'Servicio'), ('MIXTO', 'Producto y Servicio')], default='MIXTO', max_length=20, verbose_name='Rubro Principal 1 (Producto/Servicio/Mixto)'),
        ),
        migrations.AddField(
            model_name='rubro',
            name='rubro_principal_2',
            field=models.CharField(blank=True, choices=[('PRODUCTO', 'Producto'), ('SERVICIO', 'Servicio'), ('MIXTO', 'Producto y Servicio')], max_length=20, null=True, verbose_name='Rubro Principal 2 (opcional, sub-rubro mixto)'),
        ),
        migrations.AddField(
            model_name='rubro',
            name='google_categories',
            field=models.ManyToManyField(blank=True, related_name='rubros', to='geo.googlecategory', verbose_name='Google Categories asociadas (M2M)'),
        ),
        migrations.AddField(
            model_name='rubro',
            name='google_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rubros_primary', to='geo.googlecategory', verbose_name='Google Category principal (FK)'),
        ),
        migrations.CreateModel(
            name='RubroDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ATENCION', 'Atención al Cliente'), ('PRODUCTO', 'Producto / Servicio'), ('ESPACIO', 'Espacio / Ambiente'), ('LIMPIEZA', 'Limpieza e Higiene'), ('ESPECIFICA_RUBRO', 'Específica del Rubro')], default='ATENCION', max_length=30, verbose_name='Tipo de Dimensión')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre dimensión (mostrar en UI)')),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensiones', to='geo.rubro', verbose_name='Rubro')),
            ],
            options={
                'verbose_name': 'Dimensión Rubro',
                'verbose_name_plural': 'Dimensiones Rubros',
                'ordering': ['rubro__orden', 'orden', 'tipo'],
                'unique_together': {('rubro', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='RubroDimensionAtributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre atributo (keyword detectar en reseña)')),
                ('sinonimos', models.JSONField(blank=True, default=list, help_text='Keywords adicionales para match en reseñas (sinónimos, variantes).')),
                ('ponderacion', models.PositiveSmallIntegerField(default=1, verbose_name='Ponderación para cálculo score dimensión')),
                ('orden', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='geo.rubrodimension', verbose_name='Dimensión')),
            ],
            options={
                'verbose_name': 'Atributo Dimensión',
                'verbose_name_plural': 'Atributos Dimensiones',
                'ordering': ['dimension__rubro__orden', 'dimension__orden', 'orden', 'nombre'],
                'unique_together': {('dimension', 'nombre')},
            },
        ),
    ]
