# Generated by Django 5.1.3 on 2026-08-12 03:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benchmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('posicion_local', models.IntegerField()),
                ('total_evaluados', models.IntegerField()),
                ('puntuacion_local', models.DecimalField(decimal_places=2, max_digits=5)),
                ('puntuacion_promedio_rubro', models.DecimalField(decimal_places=2, max_digits=5)),
                ('top25_promedio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bottom25_promedio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benchmarks', to='businesses.local')),
            ],
            options={
                'verbose_name': 'Benchmark',
                'verbose_name_plural': 'Benchmarks',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='ResenaGoogle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('google_review_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('autor_nombre', models.CharField(max_length=255)),
                ('autor_foto_url', models.CharField(blank=True, max_length=500, null=True)),
                ('calificacion', models.IntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_google', models.DateTimeField()),
                ('fecha_captura', models.DateTimeField(auto_now_add=True)),
                ('sentimiento', models.CharField(blank=True, choices=[('POSITIVO', 'Positivo'), ('NEUTRO', 'Neutro'), ('NEGATIVO', 'Negativo')], max_length=10, null=True)),
                ('score_sentimiento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('corregido_por_usuario', models.BooleanField(default=False)),
                ('sentimiento_corregido', models.CharField(blank=True, choices=[('POSITIVO', 'Positivo'), ('NEUTRO', 'Neutro'), ('NEGATIVO', 'Negativo')], max_length=10, null=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='businesses.local')),
            ],
            options={
                'verbose_name': 'Reseña Google',
                'verbose_name_plural': 'Reseñas Google',
                'ordering': ['-fecha_google'],
            },
        ),
    ]
