# Generated by Django 5.1.3 on 2026-09-15 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0007_local_businesses__negocio_b0b44d_idx_and_more'),
        ('reputation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resenagoogle',
            name='sub_ratings',
            field=models.JSONField(blank=True, default=dict, help_text='Sub-ratings por rubro: Atención al cliente, Valoración de productos, Espacio físico / Ambiente'),
        ),
        migrations.AddIndex(
            model_name='resenagoogle',
            index=models.Index(fields=['local', '-fecha_google'], name='reputation__local_i_e26ca2_idx'),
        ),
        migrations.AddIndex(
            model_name='resenagoogle',
            index=models.Index(fields=['calificacion'], name='reputation__calific_f86698_idx'),
        ),
        migrations.AddIndex(
            model_name='resenagoogle',
            index=models.Index(fields=['sentimiento'], name='reputation__sentimi_ce0d0f_idx'),
        ),
    ]
