# Generated by Django 5.1.3 on 2026-08-18 02:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0004_local_comuna_negocio_comuna_negocio_rubro'),
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaEncuesta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre interno plantilla')),
                ('nombre_mostrar', models.CharField(blank=True, max_length=200, null=True, verbose_name='Título público')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción para el cliente')),
                ('orden', models.IntegerField(default=10, verbose_name='Orden visual')),
                ('activar_nps', models.BooleanField(default=True, verbose_name='Pregunta NPS (0-10)')),
                ('titulo_nps', models.CharField(default='¿Qué tan probable es que nos recomiendes a un familiar o amigo?', max_length=200, verbose_name='Título pregunta NPS')),
                ('activar_csat', models.BooleanField(default=True, verbose_name='Pregunta CSAT (Carita de satisfacción')),
                ('titulo_csat', models.CharField(default='¿Qué tan satisfecho estás con la atención recibida hoy?', max_length=200, verbose_name='Título pregunta CSAT')),
                ('activar_comentario', models.BooleanField(default=True, verbose_name='Comentario libre')),
                ('titulo_comentario', models.CharField(default='¿Quieres agregar un comentario sobre tu experiencia? (opcional)', max_length=200, verbose_name='Título campo comentario')),
                ('comentario_requerido', models.BooleanField(default=False, verbose_name='Comentario obligatorio')),
                ('preguntas_extra', models.JSONField(blank=True, default=list, verbose_name='Preguntas extra custom JSON (futuro')),
                ('activa', models.BooleanField(default=True, verbose_name='Plantilla activa')),
                ('es_default', models.BooleanField(default=False, verbose_name='Plantilla default para nuevos locales')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha actualización')),
                ('rubros', models.ManyToManyField(blank=True, related_name='plantillas_encuesta', to='geo.rubro', verbose_name='Rubros donde se aplica (vacío = todos')),
            ],
            options={
                'verbose_name': 'Plantilla de encuesta',
                'verbose_name_plural': 'Plantillas de encuestas',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaEncuesta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nps_puntaje', models.IntegerField(verbose_name='NPS (0-10)')),
                ('csat_emocion', models.CharField(blank=True, choices=[('MUY_FELIZ', 'Muy Feliz (5/5)'), ('FELIZ', 'Feliz (4/5)'), ('NEUTRAL', 'Neutral (3/5)'), ('INSATISFECHO', 'Insatisfecho (2/5)'), ('MUY_INSATISFECHO', 'Muy Insatisfecho (1/5)')], max_length=30, null=True, verbose_name='CSAT emoción')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario cliente')),
                ('email_opcional', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email cliente (opcional, para contacto)')),
                ('origen', models.CharField(choices=[('QR_IMPRESO', 'QR impreso en local'), ('QR_WEB', 'Código QR web / link directo'), ('MANUAL', 'Registro manual de cliente'), ('EMAIL', 'Invitación por email')], default='QR_IMPRESO', max_length=30, verbose_name='Origen respuesta')),
                ('es_anonima', models.BooleanField(default=False, verbose_name='Cliente autoriza ser contactado')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata navegador/dispositivo')),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora de respuesta')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_encuesta', to='businesses.local', verbose_name='Local QR')),
                ('plantilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas', to='encuestas.plantillaencuesta', verbose_name='Plantilla usada')),
            ],
            options={
                'verbose_name': 'Respuesta de encuesta',
                'verbose_name_plural': 'Respuestas de encuestas',
                'ordering': ['-fecha_respuesta'],
                'indexes': [models.Index(fields=['local', '-fecha_respuesta'], name='encuestas_r_local_i_92154b_idx'), models.Index(fields=['local_id'], name='encuestas_r_local_i_97162f_idx')],
            },
        ),
    ]
