# Generated by Django 5.1.3 on 2026-09-15 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_local_qr_color_fondo_local_qr_color_primario_and_more'),
        ('encuestas', '0001_initial'),
        ('geo', '0002_googlecategory_rubro_rubro_principal_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantillaencuesta',
            name='color_fondo',
            field=models.CharField(default='#f8fafc', max_length=7, verbose_name='Color de fondo UI (HEX)'),
        ),
        migrations.AddField(
            model_name='plantillaencuesta',
            name='color_primario',
            field=models.CharField(default='#0f172a', max_length=7, verbose_name='Color primario UI (HEX)'),
        ),
        migrations.AddField(
            model_name='plantillaencuesta',
            name='color_secundario',
            field=models.CharField(default='#2563eb', max_length=7, verbose_name='Color secundario UI (HEX)'),
        ),
        migrations.AddField(
            model_name='plantillaencuesta',
            name='logo_custom',
            field=models.ImageField(blank=True, null=True, upload_to='encuestas/logos/', verbose_name='Logo personalizado para encuesta'),
        ),
        migrations.AddField(
            model_name='plantillaencuesta',
            name='negocio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_custom', to='businesses.negocio', verbose_name='Negocio dueño (null si es plantilla global)'),
        ),
        migrations.AlterField(
            model_name='plantillaencuesta',
            name='rubros',
            field=models.ManyToManyField(blank=True, related_name='plantillas_encuesta', to='geo.rubro', verbose_name='Rubros donde se aplica (vacío = todos)'),
        ),
    ]
