# Generated by Django 5.1.3 on 2026-08-29 17:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaAdmin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usuario_email', models.EmailField(blank=True, help_text='Cache del email por si el usuario se elimina posteriormente.', max_length=254, null=True)),
                ('accion', models.CharField(choices=[('CREAR', 'Crear'), ('EDITAR', 'Editar'), ('ELIMINAR', 'Eliminar'), ('ACTIVAR', 'Activar'), ('DESACTIVAR', 'Desactivar'), ('SUSPENDER', 'Suspender'), ('CONFIRMAR', 'Confirmar'), ('CANCELAR', 'Cancelar'), ('CAMBIAR_PLAN', 'Cambiar Plan'), ('EXTENDER_DIAS', 'Extender Días'), ('REINICIAR_ONBOARDING', 'Reiniciar Onboarding'), ('RESETEAR_CLAVE', 'Resetear Clave'), ('CAMBIAR_ROL', 'Cambiar Rol'), ('REASIGNAR_DUENO', 'Reasignar Dueño'), ('MARCAR_DEFAULT', 'Marcar Default'), ('CORREGIR_SENTIMIENTO', 'Corregir Sentimiento'), ('SEED_DATOS', 'Seed / Cargar Datos'), ('OTRO', 'Otro')], db_index=True, max_length=30)),
                ('modulo', models.CharField(choices=[('SUSCRIPCIONES', 'Suscripciones'), ('NEGOCIOS', 'Negocios'), ('USUARIOS', 'Usuarios'), ('PLANES', 'Planes'), ('PLANTILLAS_ENCUESTAS', 'Plantillas Encuestas'), ('PLANTILLAS_NOTIFICACIONES', 'Plantillas Notificaciones'), ('RUBROS', 'Rubros'), ('LOCALES', 'Locales'), ('PAGOS', 'Pagos'), ('COBROS', 'Cobros'), ('RESEÑAS_GOOGLE', 'Reseñas Google'), ('RESPUESTAS_ENCUESTA', 'Respuestas Encuesta'), ('BENCHMARK', 'Benchmark'), ('OTRO', 'Otro')], db_index=True, max_length=30)),
                ('entidad_tipo', models.CharField(help_text='Nombre del modelo: ej. Suscripcion, Negocio, Plan, User', max_length=100)),
                ('entidad_id', models.CharField(help_text='UUID o ID de la entidad afectada.', max_length=255)),
                ('entidad_descripcion', models.CharField(blank=True, help_text='Descripción amigable: ej. "Café del Centro Demo - Plan MVP_Básico".', max_length=500, null=True)),
                ('datos_antes', models.JSONField(blank=True, default=dict, help_text='Estado anterior de la entidad (dict).')),
                ('datos_despues', models.JSONField(blank=True, default=dict, help_text='Estado posterior de la entidad (dict).')),
                ('notas_internas', models.TextField(blank=True, help_text='Notas que escribe el Admin Soporte al ejecutar la acción.', null=True)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_admin', to=settings.AUTH_USER_MODEL, verbose_name='Administrador que realizó la acción')),
            ],
            options={
                'verbose_name': 'Auditoría Admin Soporte',
                'verbose_name_plural': 'Auditorías Admin Soporte',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['modulo', 'accion', '-fecha_hora'], name='adminpanel__modulo_f44af9_idx'), models.Index(fields=['entidad_tipo', 'entidad_id'], name='adminpanel__entidad_a8b10d_idx'), models.Index(fields=['usuario', '-fecha_hora'], name='adminpanel__usuario_220a27_idx')],
            },
        ),
    ]
