# Generated by Django 5.1.3 on 2026-08-31 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionMetricas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bm_min_empresas', models.PositiveIntegerField(default=3, verbose_name='Cantidad mínima de empresas en el benchmark')),
                ('bm_min_valoraciones', models.PositiveIntegerField(default=10, verbose_name='Cantidad mínima de valoraciones requeridas')),
                ('bm_dias_sin_valoraciones_excluir', models.PositiveIntegerField(default=90, verbose_name='Días sin valoraciones para excluir del benchmark')),
                ('bm_filtro_temporal_default', models.CharField(choices=[('SEMANAL', 'Semanal'), ('MENSUAL', 'Mensual'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], default='MENSUAL', max_length=20, verbose_name='Filtro temporal predeterminado')),
                ('bm_filtro_geografico_default', models.CharField(choices=[('5KM', 'Hasta 5 km'), ('COMUNAL', 'Comunal'), ('REGIONAL', 'Regional'), ('NACIONAL', 'Nacional')], default='COMUNAL', max_length=20, verbose_name='Filtro geográfico predeterminado')),
                ('bm_criterio_desempate', models.CharField(choices=[('DECIMAS', 'Décimas de valoración'), ('POSITIVAS_PERIODO', 'Valoraciones positivas del último mes/semestre')], default='DECIMAS', max_length=30, verbose_name='Criterio de desempate')),
                ('bm_nota_explicativa_usuario', models.TextField(default='Los criterios de benchmark determinan la muestra mínima de empresas y opiniones requeridas para comparar el rendimiento de tu negocio en tu rubro y zona geográfica.', verbose_name='Explicación de criterios visible en Dashboard de Usuario')),
                ('csat_nps_criterio_metodologico', models.TextField(default='CSAT (% respuestas de 4 y 5 estrellas / caritas felices) y NPS (% Promotores [9-10] menos % Detractores [0-6]).', verbose_name='Criterio metodológico de cálculo')),
                ('csat_nps_min_empresas_benchmark', models.PositiveIntegerField(default=3, verbose_name='Cantidad mínima de empresas para benchmark por rubro')),
                ('csat_nps_min_valoraciones', models.PositiveIntegerField(default=5, verbose_name='Cantidad mínima de valoraciones para aparecer en benchmark')),
                ('csat_nps_dias_sin_valoraciones_excluir', models.PositiveIntegerField(default=60, verbose_name='Días sin valoraciones para excluir del benchmark')),
                ('csat_nps_filtro_temporal_default', models.CharField(choices=[('SEMANAL', 'Semanal'), ('MENSUAL', 'Mensual'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], default='MENSUAL', max_length=20, verbose_name='Filtro temporal default CSAT/NPS')),
                ('csat_nps_filtro_geografico_default', models.CharField(choices=[('5KM', 'Hasta 5 km'), ('COMUNAL', 'Comunal'), ('REGIONAL', 'Regional'), ('NACIONAL', 'Nacional')], default='COMUNAL', max_length=20, verbose_name='Filtro geográfico default CSAT/NPS')),
                ('csat_nps_criterio_desempate', models.CharField(choices=[('DECIMAS', 'Décimas de valoración'), ('POSITIVAS_PERIODO', 'Valoraciones positivas del último mes/semestre')], default='DECIMAS', max_length=30, verbose_name='Criterio de desempate CSAT/NPS')),
                ('resenas_minimo_para_analisis', models.PositiveIntegerField(default=5, verbose_name='Mínimo de reseñas para realizar análisis')),
                ('resenas_categorias_agrupacion', models.JSONField(blank=True, default=list, verbose_name='Categorías de agrupación de reseñas')),
                ('resenas_dias_sin_valoraciones_no_mostrar', models.PositiveIntegerField(default=120, verbose_name='Rango de tiempo sin valoraciones para ocultar análisis en la app')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Métricas',
                'verbose_name_plural': 'Configuración de Métricas',
            },
        ),
    ]
