# Generated by Django 5.1.3 on 2026-09-15 02:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_configuracionmetricas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudARCOPB',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_solicitante', models.CharField(max_length=200)),
                ('email_solicitante', models.EmailField(max_length=254)),
                ('rut_solicitante', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_solicitud', models.CharField(default='ELIMINACION_DATOS', max_length=50)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('RESUELTO', 'Resuelto / Finalizado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('notas_admin', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_arco', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud ARCOPB',
                'verbose_name_plural': 'Solicitudes ARCOPB',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
