# Generated by Django 5.1.3 on 2026-08-12 03:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del local')),
                ('direccion', models.CharField(blank=True, max_length=500, null=True, verbose_name='Dirección')),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('latitud', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True, verbose_name='Latitud')),
                ('longitud', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True, verbose_name='Longitud')),
                ('google_place_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Google Place ID')),
                ('horario', models.JSONField(blank=True, null=True, verbose_name='Horario')),
                ('qr_token', models.CharField(max_length=255, unique=True, verbose_name='Token QR')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('CERRADO', 'Cerrado')], default='ACTIVO', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locales',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Competidor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del competidor')),
                ('google_place_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Google Place ID')),
                ('direccion', models.CharField(blank=True, max_length=500, null=True, verbose_name='Dirección')),
                ('latitud', models.DecimalField(decimal_places=15, max_digits=18, verbose_name='Latitud')),
                ('longitud', models.DecimalField(decimal_places=15, max_digits=18, verbose_name='Longitud')),
                ('distancia_km', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Distancia (km)')),
                ('rubro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Rubro')),
                ('calificacion_global', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Calificación global')),
                ('numero_opiniones', models.IntegerField(blank=True, null=True, verbose_name='Número de opiniones')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('CERRADO', 'Cerrado')], default='ACTIVO', max_length=20, verbose_name='Estado')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competidores', to='businesses.local', verbose_name='Local')),
            ],
            options={
                'verbose_name': 'Competidor',
                'verbose_name_plural': 'Competidores',
                'ordering': ['distancia_km'],
            },
        ),
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del negocio')),
                ('rut', models.CharField(blank=True, max_length=20, null=True, verbose_name='RUT')),
                ('rubro_google', models.CharField(blank=True, max_length=255, null=True, verbose_name='Rubro (Google)')),
                ('direccion', models.CharField(blank=True, max_length=500, null=True, verbose_name='Dirección')),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email_contacto', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de contacto')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='negocios/logos/', verbose_name='Logo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_verificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de verificación')),
                ('verificado', models.BooleanField(default=False, verbose_name='Verificado')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido'), ('ELIMINADO', 'Eliminado')], default='ACTIVO', max_length=20, verbose_name='Estado')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('dueño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negocios', to=settings.AUTH_USER_MODEL, verbose_name='Dueño')),
            ],
            options={
                'verbose_name': 'Negocio',
                'verbose_name_plural': 'Negocios',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='local',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locales', to='businesses.negocio', verbose_name='Negocio'),
        ),
        migrations.CreateModel(
            name='SnapshotReputacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_captura', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de captura')),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Calificación')),
                ('opiniones', models.IntegerField(blank=True, null=True, verbose_name='Opiniones')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='Ranking')),
                ('datos', models.JSONField(blank=True, null=True, verbose_name='Datos adicionales')),
                ('competidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='businesses.competidor', verbose_name='Competidor')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots_local', to='businesses.local', verbose_name='Local')),
            ],
            options={
                'verbose_name': 'Snapshot de reputación',
                'verbose_name_plural': 'Snapshots de reputación',
                'ordering': ['-fecha_captura'],
            },
        ),
    ]
