# Generated by Django 5.1.3 on 2026-08-13 01:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MiembroEquipo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rol', models.CharField(choices=[('DUENO', 'Dueño'), ('USUARIO_EQUIPO', 'Usuario de Equipo'), ('GESTOR', 'Gestor (solo lectura + gestión encuestas)')], default='USUARIO_EQUIPO', max_length=20, verbose_name='Rol en el negocio')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('PENDIENTE', 'Pendiente de invitación'), ('DESACTIVADO', 'Desactivado')], default='ACTIVO', max_length=20, verbose_name='Estado')),
                ('permisos', models.JSONField(blank=True, default=list, help_text='Lista de permisos específicos (usar PermisosChoices). Si rol=DUEÑO, se ignoran.', verbose_name='Permisos específicos')),
                ('fecha_invitacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de invitación')),
                ('fecha_aceptacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aceptación')),
                ('invitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miembros_invitados', to=settings.AUTH_USER_MODEL, verbose_name='Invitado por')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros_equipo', to='businesses.negocio', verbose_name='Negocio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias_negocios', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Miembro de equipo',
                'verbose_name_plural': 'Miembros de equipo',
                'ordering': ['negocio', 'rol', 'fecha_invitacion'],
                'unique_together': {('negocio', 'usuario')},
            },
        ),
    ]
