# Generated by Django 5.1.3 on 2026-08-17 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_miembroequipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='onboarding_fecha_paso1',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Paso 1 (registro)'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='onboarding_fecha_paso2',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Paso 2 (datos negocio)'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='onboarding_fecha_paso3',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Paso 3 (confirmación)'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='onboarding_paso1_completo',
            field=models.BooleanField(default=False, verbose_name='Onboarding Paso 1 Registro completo'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='onboarding_paso2_completo',
            field=models.BooleanField(default=False, verbose_name='Onboarding Paso 2 Datos Negocio/Local completo'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='onboarding_paso3_completo',
            field=models.BooleanField(default=False, verbose_name='Onboarding Paso 3 Confirmación Plan completo'),
        ),
    ]
