# Generated by Django 5.1.3 on 2026-08-18 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_negocio_onboarding_fecha_paso1_and_more'),
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='comuna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locales', to='geo.comuna', verbose_name='Comuna'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='comuna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='negocios', to='geo.comuna', verbose_name='Comuna'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='rubro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='negocios', to='geo.rubro', verbose_name='Rubro del negocio'),
        ),
    ]
