# Generated by Django 5.1.3 on 2026-08-25 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_local_comuna_negocio_comuna_negocio_rubro'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='acepto_politica_datos',
            field=models.DateField(blank=True, help_text='LOPD N°19.628 / RGPD. Se guarda la fecha en la cual el dueño aceptó.', null=True, verbose_name='Fecha aceptación Política de Protección de Datos'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='rango_empleados',
            field=models.CharField(blank=True, choices=[('R1', '1 persona'), ('R2', '2 personas'), ('R3_5', '3 a 5 personas'), ('R6_15', '6 a 15 personas'), ('R16_MAS', '16 o más personas')], help_text='Tamaño de equipo del negocio.', max_length=10, null=True, verbose_name='Rango de empleados'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='razon_social',
            field=models.CharField(blank=True, help_text='Nombre legal de la empresa (SII). Requerido en el onboarding Paso 2.', max_length=255, null=True, verbose_name='Razón Social'),
        ),
        migrations.AlterField(
            model_name='miembroequipo',
            name='permisos',
            field=models.JSONField(blank=True, default=list, help_text='Lista de permisos específicos (usar PermisosChoices). Si rol=DUEÑO, se ignoran. Roles ADMINISTRADOR_LOCAL tienen todos los permisos salvo GESTIONAR_CUENTA.', verbose_name='Permisos específicos'),
        ),
        migrations.AlterField(
            model_name='miembroequipo',
            name='rol',
            field=models.CharField(choices=[('DUENO', 'Dueño'), ('ADMINISTRADOR_LOCAL', 'Administrador Completo Local'), ('GESTOR', 'Gestor (solo lectura + gestión encuestas)'), ('USUARIO_EQUIPO', 'Usuario de Equipo'), ('VISUALIZADOR_DESCARGA', 'Visualizador / Descarga Información')], default='USUARIO_EQUIPO', max_length=30, verbose_name='Rol en el negocio'),
        ),
    ]
