# Generated by Django 5.1.3 on 2026-08-25 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_negocio_acepto_politica_datos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='qr_color_fondo',
            field=models.CharField(blank=True, default='#FFFFFF', help_text='Recomendado blanco o colores muy claros para legibilidad impresora.', max_length=12, verbose_name='Color fondo QR (blanco por defecto)'),
        ),
        migrations.AddField(
            model_name='local',
            name='qr_color_primario',
            field=models.CharField(blank=True, default='#4F46E5', help_text='Hex color (ej: #4F46E5 = Indigo ClientBeat).', max_length=12, verbose_name='Color primario QR (módulos oscuros)'),
        ),
        migrations.AddField(
            model_name='local',
            name='qr_color_secundario',
            field=models.CharField(blank=True, default='#7C3AED', help_text='Hex color para esquinas/degradado/estilo glass.', max_length=12, verbose_name='Color secundario QR (acento/degradado)'),
        ),
        migrations.AddField(
            model_name='local',
            name='qr_encabezado',
            field=models.CharField(blank=True, default='Califica tu experiencia', help_text='Título arriba del código QR (ej: "Ayúdanos a mejorar").', max_length=80, verbose_name='Encabezado arriba del QR (máximo 80 caracteres)'),
        ),
        migrations.AddField(
            model_name='local',
            name='qr_error_level',
            field=models.CharField(choices=[('L', 'L - Bajo (7%)'), ('M', 'M - Medio (15%)'), ('Q', 'Q - Alto (25%)'), ('H', 'H - Máximo (30%, recomendado con logo)')], default='H', help_text='Si tiene logo, usar H (30%) es el default recomendado.', max_length=3, verbose_name='Nivel corrección de errores QR'),
        ),
        migrations.AddField(
            model_name='local',
            name='qr_estilo_borde',
            field=models.BooleanField(default=True, verbose_name='Borde glassmorphism y logo ClientBeat en esquina'),
        ),
        migrations.AddField(
            model_name='local',
            name='qr_logo',
            field=models.ImageField(blank=True, help_text='Recomendado 200x200px PNG. Si está vacío usa el logo del negocio o el default ClientBeat.', null=True, upload_to='locales/qr_logos/', verbose_name='Logo personalizado QR (PNG/SVG transparente 512px)'),
        ),
        migrations.AddField(
            model_name='local',
            name='qr_mostrar_logo',
            field=models.BooleanField(default=True, verbose_name='Mostrar logo centro del QR (si hay logo disponible)'),
        ),
        migrations.AddField(
            model_name='local',
            name='qr_tamano_pixels',
            field=models.PositiveSmallIntegerField(default=1024, help_text='Recomendado impresión 1024px o 2048px; web 512px OK.', verbose_name='Tamaño del QR en píxeles (cuadrado, LxL)'),
        ),
        migrations.AddField(
            model_name='local',
            name='qr_texto_corto',
            field=models.CharField(blank=True, default='¡Gracias por tu visita!', help_text='Aparece impreso bajo el código QR en el PDF/PNG descargable.', max_length=80, verbose_name='Línea de texto bajo el QR (máximo 80 caracteres)'),
        ),
    ]
