# Generated by Django 5.1.3 on 2026-09-15 23:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_local_qr_color_fondo_local_qr_color_primario_and_more'),
        ('geo', '0002_googlecategory_rubro_rubro_principal_1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='local',
            index=models.Index(fields=['negocio'], name='businesses__negocio_b0b44d_idx'),
        ),
        migrations.AddIndex(
            model_name='local',
            index=models.Index(fields=['comuna'], name='businesses__comuna__27d12e_idx'),
        ),
        migrations.AddIndex(
            model_name='local',
            index=models.Index(fields=['estado'], name='businesses__estado_525b03_idx'),
        ),
        migrations.AddIndex(
            model_name='local',
            index=models.Index(fields=['qr_token'], name='businesses__qr_toke_e2780b_idx'),
        ),
        migrations.AddIndex(
            model_name='negocio',
            index=models.Index(fields=['dueño'], name='businesses__dueño_i_843281_idx'),
        ),
        migrations.AddIndex(
            model_name='negocio',
            index=models.Index(fields=['estado'], name='businesses__estado_7f94a3_idx'),
        ),
        migrations.AddIndex(
            model_name='negocio',
            index=models.Index(fields=['comuna'], name='businesses__comuna__ddd43c_idx'),
        ),
        migrations.AddIndex(
            model_name='negocio',
            index=models.Index(fields=['rubro'], name='businesses__rubro_i_2033bf_idx'),
        ),
    ]
