# Generated by Django 5.1.3 on 2026-09-30 01:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0007_local_businesses__negocio_b0b44d_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitacionEquipo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico del colaborador')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del colaborador')),
                ('rol', models.CharField(choices=[('DUENO', 'Dueño'), ('ADMINISTRADOR_LOCAL', 'Administrador Completo Local'), ('GESTOR', 'Gestor (solo lectura + gestión encuestas)'), ('USUARIO_EQUIPO', 'Usuario de Equipo'), ('VISUALIZADOR_DESCARGA', 'Visualizador / Descarga Información')], default='USUARIO_EQUIPO', max_length=30, verbose_name='Rol en el negocio')),
                ('token', models.CharField(max_length=100, unique=True, verbose_name='Token de invitación')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('fecha_invitacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de invitación')),
                ('fecha_aceptacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aceptación')),
                ('invitado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Invitado por')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_equipo', to='businesses.negocio', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Invitación de equipo',
                'verbose_name_plural': 'Invitaciones de equipo',
                'ordering': ['-fecha_invitacion'],
            },
        ),
    ]
